### ISSUE TITLE
installing buildstream on fresh jessie from instructions at http://buildstream.gitlab.io/buildstream/install.html#installing

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#16]
In GitLab by @devcurmudgeon on Apr 25, 2017, 14:13

- the git clone fails unless we have an ssh key set, so let's replace "git clone git@gitlab.com:BuildStream/buildstream.git" with "git clone https://gitlab.com/BuildStream/buildstream.git

- ruamel fails to install...

```
Unpacking /home/admin/src/buildstream
  Running setup.py (path:/tmp/pip-rxu1im61-build/setup.py) egg_info for package from file:///home/admin/src/buildstream
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-rxu1im61-build/pytest_runner-2.11.1-py3.4.egg
    
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3/dist-packages (from BuildStream==0.1)
Downloading/unpacking psutil (from BuildStream==0.1)
  Downloading psutil-5.2.2.tar.gz (348kB): 348kB downloaded
  Running setup.py (path:/tmp/pip-build-xy965he4/psutil/setup.py) egg_info for package psutil
    
    warning: manifest_maker: MANIFEST.in, line 14: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*' found under directory '.ci'
Downloading/unpacking ruamel.yaml (from BuildStream==0.1)
  Downloading ruamel.yaml-0.14.9.tar.gz (241kB): 241kB downloaded
  Running setup.py (path:/tmp/pip-build-xy965he4/ruamel.yaml/setup.py) egg_info for package ruamel.yaml
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2382, in _dep_map
        return self.__dep_map
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2457, in __getattr__
        raise AttributeError(attr)
    AttributeError: _Distribution__dep_map
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-xy965he4/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/tmp/pip-build-xy965he4/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 300, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2201, in require
        reqs = self.dist.requires(self.extras)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2401, in requires
        dm = self._dep_map
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2390, in _dep_map
        if invalid_marker(marker):
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1207, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1319, in _markerlib_evaluate
        for key in env.keys():
    RuntimeError: dictionary changed size during iteration
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2382, in _dep_map

    return self.__dep_map

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2457, in __getattr__

    raise AttributeError(attr)

AttributeError: _Distribution__dep_map



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-xy965he4/ruamel.yaml/setup.py", line 858, in <module>

    main()

  File "/tmp/pip-build-xy965he4/ruamel.yaml/setup.py", line 847, in main

    setup(**kw)

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__

    self.finalize_options()

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 300, in finalize_options

    ep.require(installer=self.fetch_build_egg)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2201, in require

    reqs = self.dist.requires(self.extras)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2401, in requires

    dm = self._dep_map

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2390, in _dep_map

    if invalid_marker(marker):

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1207, in is_invalid_marker

    cls.evaluate_marker(text)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1319, in _markerlib_evaluate

    for key in env.keys():

RuntimeError: dictionary changed size during iteration

sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']

test compiling test_ruamel_yaml

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-xy965he4/ruamel.yaml
Storing debug log for failure in /home/admin/.pip/pip.log
```

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Apr 26, 2017, 11:30

closed

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Apr 26, 2017, 11:30

Thanks for the report and details !

I've fixed this in master with the following commit:

```
commit b88538309217b29d4df881e1b86b0e1f12eb91d8
Author: Tristan Van Berkom <tristan.vanberkom@codethink.co.uk>
Date:   Wed Apr 26 20:27:55 2017 +0900

    Documentation fixes for issue 12
    
      o Use the https gitlab url since the git url scheme requires you
        have a gitlab ssh key
    
      o Recommend installing ruamel.yaml with the package manager, as
        people are running into issues installing ruamel.yaml via pip

```
