### ISSUE TITLE
Rare exception when terminating processes

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#24]
In GitLab by @tristanvb on May 2, 2017, 10:22

In some corner cases, we are experiencing the symptoms described in this [python upstream bug report](https://bugs.python.org/issue24484)

This is mostly harmless, but is nevertheless a stack trace thrown at the user for no good reason, e.g.:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/util.py", line 288, in _exit_function
    _run_finalizers(0)
  File "/usr/lib/python3.5/multiprocessing/util.py", line 248, in _run_finalizers
    items = [x for x in list(_finalizer_registry.items()) if f(x)]
RuntimeError: dictionary changed size during iteration
```

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Aug 22, 2017, 17:22

This hasn't happened in a long time, I think it's been addressed by using `os._exit()` from `SIGTERM` handlers.

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Aug 22, 2017, 17:22

closed

**Comment by cs-shadow** [comment]
In GitLab by @tacgomes on Jul 27, 2018, 10:38

reopened

**Comment by cs-shadow** [comment]
In GitLab by @tacgomes on Jul 27, 2018, 10:39

This is frequently happening when building the freedesktop-sdk in the CI: https://gitlab.com/BuildStream/buildstream/-/jobs/84724565

**Comment by cs-shadow** [comment]
In GitLab by @franred on Aug 7, 2018, 09:28

In [python upstream bug report](https://bugs.python.org/issue24484) is marked as resolved and ported to 3.5, 3.6 and 2.7. So I would expect that the issue goes away when the distros ship the new version of 3.5.

@tacgomes, @tristanvb, Should we mark this as won't fix or force the buildstream to use 3.5.3 at least [patch ported to 3.5 MR](https://github.com/python/cpython/pull/2167) ?

**Comment by cs-shadow** [comment]
In GitLab by @tacgomes on Aug 7, 2018, 10:34

Note that on the link that I've posted above the Python version used seems to be 3.5.

**Comment by cs-shadow** [comment]
In GitLab by @tacgomes on Aug 17, 2018, 15:28

marked this issue as related to #593
