### ISSUE TITLE
failed to upgrade buildstream at 640a734ec1db923b5

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#26]
In GitLab by @devcurmudgeon on May 7, 2017, 11:49

```
admin@ip-172-31-2-103:~/src/buildstream$ pip3 install --user .
Unpacking /home/admin/src/buildstream
  Running setup.py (path:/tmp/pip-j55sp20f-build/setup.py) egg_info for package from file:///home/admin/src/buildstream
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-j55sp20f-build/pytest_runner-2.11.1-py3.4.egg
    
  Requirement already satisfied (use --upgrade to upgrade): BuildStream==0.1 from file:///home/admin/src/buildstream in /home/admin/.local/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3/dist-packages (from BuildStream==0.1)
Requirement already satisfied (use --upgrade to upgrade): psutil in /home/admin/.local/lib/python3.4/site-packages (from BuildStream==0.1)
Requirement already satisfied (use --upgrade to upgrade): ruamel.yaml in /usr/lib/python3/dist-packages (from BuildStream==0.1)
Requirement already satisfied (use --upgrade to upgrade): pluginbase in /home/admin/.local/lib/python3.4/site-packages (from BuildStream==0.1)
Requirement already satisfied (use --upgrade to upgrade): Click in /home/admin/.local/lib/python3.4/site-packages (from BuildStream==0.1)
Requirement already satisfied (use --upgrade to upgrade): blessings in /home/admin/.local/lib/python3.4/site-packages (from BuildStream==0.1)
Requirement already satisfied (use --upgrade to upgrade): typing in /home/admin/.local/lib/python3.4/site-packages (from ruamel.yaml->BuildStream==0.1)
Cleaning up...
admin@ip-172-31-2-103:~/src/buildstream$ pip3 install --user . --upgrade
Unpacking /home/admin/src/buildstream
  Running setup.py (path:/tmp/pip-x7xvew4u-build/setup.py) egg_info for package from file:///home/admin/src/buildstream
    your setuptools is too old (<12)
    setuptools_scm functionality is degraded
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-x7xvew4u-build/pytest_runner-2.11.1-py3.4.egg
    
Downloading/unpacking setuptools from https://pypi.python.org/packages/27/45/79618f80704497f74f2de1ca62216a5c3ffdbd49f43047c81c30e126a055/setuptools-35.0.2-py2.py3-none-any.whl#md5=54a3dac8fe9b912bb884a485d9a2e9cb (from BuildStream==0.1)
  Downloading setuptools-35.0.2-py2.py3-none-any.whl (390kB): 390kB downloaded
Requirement already up-to-date: psutil in /home/admin/.local/lib/python3.4/site-packages (from BuildStream==0.1)
Downloading/unpacking ruamel.yaml from https://pypi.python.org/packages/5a/86/8df701c9de786f25f5f290d1e0b63374becd79149298b86527ebae83f130/ruamel.yaml-0.14.11.tar.gz#md5=9db79fd50c560c2fc38a511354fabd65 (from BuildStream==0.1)
  Downloading ruamel.yaml-0.14.11.tar.gz (242kB): 242kB downloaded
  Running setup.py (path:/tmp/pip-build-koos95yw/ruamel.yaml/setup.py) egg_info for package ruamel.yaml
    /usr/lib/python3.4/importlib/_bootstrap.py:321: UserWarning: Module _ruamel_yaml was already imported from /usr/lib/python3/dist-packages/_ruamel_yaml.cpython-34m-x86_64-linux-gnu.so, but /tmp/pip-build-koos95yw/ruamel.yaml is being added to sys.path
      return f(*args, **kwds)
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-koos95yw/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/tmp/pip-build-koos95yw/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 300, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2201, in require
        reqs = self.dist.requires(self.extras)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2401, in requires
        dm = self._dep_map
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2457, in __getattr__
        raise AttributeError(attr)
    AttributeError: _dep_map
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Complete output from command python setup.py egg_info:
    /usr/lib/python3.4/importlib/_bootstrap.py:321: UserWarning: Module _ruamel_yaml was already imported from /usr/lib/python3/dist-packages/_ruamel_yaml.cpython-34m-x86_64-linux-gnu.so, but /tmp/pip-build-koos95yw/ruamel.yaml is being added to sys.path

  return f(*args, **kwds)

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-koos95yw/ruamel.yaml/setup.py", line 858, in <module>

    main()

  File "/tmp/pip-build-koos95yw/ruamel.yaml/setup.py", line 847, in main

    setup(**kw)

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python3.4/distutils/dist.py", line 280, in __init__

    self.finalize_options()

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 300, in finalize_options

    ep.require(installer=self.fetch_build_egg)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2201, in require

    reqs = self.dist.requires(self.extras)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2401, in requires

    dm = self._dep_map

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2457, in __getattr__

    raise AttributeError(attr)

AttributeError: _dep_map

sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']

test compiling test_ruamel_yaml

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-koos95yw/ruamel.yaml
Storing debug log for failure in /home/admin/.pip/pip.log
```

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on May 8, 2017, 11:58

I'm not sure how to reproduce this.

Did you uninstall a previously installed version ? Or did you *"pip install --user ."* in a git checkout after updating on a site where it was already installed ? (that is untested, I dont know that it should work or not).

Anything else specific to your setup that might help me reproduce ?

**Comment by cs-shadow** [comment]
In GitLab by @tacgomes on Sep 27, 2018, 16:42

This is one year old now and I never reproduced it. I am closing it.

**Comment by cs-shadow** [comment]
In GitLab by @tacgomes on Sep 27, 2018, 16:42

closed
