### ISSUE TITLE
Non-empty read-only directories not handled during 'bst build' and others

### ISSUE THREAD

**Issue by cs-shadow** [cs-shadow/buildstream#85]
In GitLab by @aevri on Aug 31, 2017, 14:40

It seems that non-empty read-only directories are not handled as expected.

If I construct a tar file like so:

```
mkdir files
touch files/{a,b}
chmod ugo-w files
tar cvf files.tar files
```

I cannot use it in an 'import' element as I would expect:

```
cat > tar.bst <<EOF
kind: import
description: Import shell

sources:
- kind: tar
  url: file:///src/files.tar
  base-dir: ''
EOF

bst track tar.bst
bst build tar.bst
```

The 'bst build' step fails. After re-creating the read-only directory, `os.link` fails to create a link in it:
```
[--:--:--][991e5007][ main:tar.bst  ] START   Starting build
[--:--:--][991e5007][build:tar.bst  ] START   hello-buildstream/tar/991e5007-build.92.log
[--:--:--][991e5007][build:tar.bst  ] START   Staging sources
[00:00:00][991e5007][build:tar.bst  ] SUCCESS Staging sources
[00:00:00][991e5007][build:tar.bst  ] BUG     hello-buildstream/tar/991e5007-build.92.log

    An unhandled exception occured:

    Traceback (most recent call last):
      File "/src/buildstream/buildstream/_scheduler/job.py", line 265, in child_action
        result = self.action(element)
      File "/src/buildstream/buildstream/_scheduler/buildqueue.py", line 34, in process
        element._assemble()
      File "/src/buildstream/buildstream/element.py", line 1093, in _assemble
        utils.link_files(collectdir, filesdir)
      File "/src/buildstream/buildstream/utils.py", line 386, in link_files
        _process_list(src, dest, files, safe_link, result, ignore_missing=ignore_missing)
      File "/src/buildstream/buildstream/utils.py", line 553, in _process_list
        actionfunc(srcpath, destpath, result=result)
      File "/src/buildstream/buildstream/utils.py", line 250, in safe_link
        os.link(src, dest)
    PermissionError: [Errno 13] Permission denied: '/tmp/home/.cache/buildstream/build/tar-5djrnjyl/root/output/files/a' -> '/tmp/home/.cache/buildstream/build/tar-5djrnjyl/root/tmpwf74shc0/files/files/a'
```

If you do this as root user, it of course succeeds because root ignores permissions. Interestingly, a subsequent `bst checkout` as root will fail with a similar error though. Perhaps it copies as user 'tomjon', and inside the sandbox.

**Comment by cs-shadow** [comment]
In GitLab by @tlater on Sep 27, 2017, 14:00

created branch [`81-non-empty-read-only-directories-not-handled-during-bst-build-and-others`](https://gitlab.com/BuildStream/buildstream/compare/master...81-non-empty-read-only-directories-not-handled-during-bst-build-and-others)

**Comment by cs-shadow** [comment]
In GitLab by @tlater on Sep 28, 2017, 14:24

mentioned in commit buildstream-tests@512c87e367e015338fff38287f7bacbc73ca71a4

**Comment by cs-shadow** [comment]
In GitLab by @tlater on Sep 28, 2017, 14:27

mentioned in merge request buildstream-tests!16

**Comment by cs-shadow** [comment]
In GitLab by @tlater on Sep 29, 2017, 17:12

mentioned in commit buildstream-tests@3facba7de7aeef6a438c2e8f9a0841eada1f0eda

**Comment by cs-shadow** [comment]
In GitLab by @tlater on Sep 29, 2017, 17:13

mentioned in commit buildstream-tests@c3748ba92007b36460dbd413c457d52918cde8bd

**Comment by cs-shadow** [comment]
In GitLab by @tlater on Sep 29, 2017, 17:24

mentioned in merge request !100

**Comment by cs-shadow** [comment]
In GitLab by @tlater on Oct 2, 2017, 09:44

mentioned in commit buildstream-tests@5166e0580cf33bb63fda0cc9be23cbaacf924292

**Comment by cs-shadow** [comment]
In GitLab by @tlater on Oct 2, 2017, 10:23

mentioned in commit buildstream-tests@61903a6e38c91802371fdbdfd8c4a2d85b4d1fd2

**Comment by cs-shadow** [comment]
In GitLab by @tlater on Oct 2, 2017, 11:29

mentioned in commit buildstream-tests@8bb3eb247a0dc179790619b02d96ec486f960367

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Oct 13, 2017, 07:20

Just merged !100 with some modifications.

Looks like the buildstream-tests related MR is blocking on resolution of #102 ... short of that there is no way to CI test this issue.

While that happens, can someone verify that this is actually fixed the problem ?

**Comment by cs-shadow** [comment]
In GitLab by @aevri on Oct 13, 2017, 10:46

It's improved! Only half-fixed though perhaps.

It now successfully stages and caches but fails to clean up. `bst checkout` works as expected on the cached result.

I tested with BuildStream at commit 58a1dd4ba9aef43a47d7dd24deee6eb9e9e45b30 "_plugincontext.py: Fix third party plugin loading", re-running the original repro I now see this error instead:

```
[--:--:--][fa7d4306][ main:tar2.bst  ] START   Starting build
[--:--:--][fa7d4306][build:tar2.bst  ] START   hello-buildstream/tar2/fa7d4306-build.202.log
[--:--:--][fa7d4306][build:tar2.bst  ] START   Staging sources
[00:00:00][fa7d4306][build:tar2.bst  ] SUCCESS Staging sources
[--:--:--][fa7d4306][build:tar2.bst  ] START   Caching Artifact
[00:00:00][fa7d4306][build:tar2.bst  ] SUCCESS Caching Artifact
[00:00:00][fa7d4306][build:tar2.bst  ] BUG     hello-buildstream/tar2/fa7d4306-build.202.log

    An unhandled exception occured:

    Traceback (most recent call last):
      File "/tmp/buildstream/buildstream/_scheduler/job.py", line 266, in child_action
        result = self.action(element)
      File "/tmp/buildstream/buildstream/_scheduler/buildqueue.py", line 34, in process
        element._assemble()
      File "/tmp/buildstream/buildstream/element.py", line 1124, in _assemble
        raise
      File "/usr/lib64/python3.6/tempfile.py", line 807, in __exit__
        self.cleanup()
      File "/usr/lib64/python3.6/tempfile.py", line 811, in cleanup
        _shutil.rmtree(self.name)
      File "/usr/lib64/python3.6/shutil.py", line 480, in rmtree
        _rmtree_safe_fd(fd, path, onerror)
      File "/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd
        _rmtree_safe_fd(dirfd, fullname, onerror)
      File "/usr/lib64/python3.6/shutil.py", line 418, in _rmtree_safe_fd
        _rmtree_safe_fd(dirfd, fullname, onerror)
      File "/usr/lib64/python3.6/shutil.py", line 438, in _rmtree_safe_fd
        onerror(os.unlink, fullname, sys.exc_info())
      File "/usr/lib64/python3.6/shutil.py", line 436, in _rmtree_safe_fd
        os.unlink(name, dir_fd=topfd)
    PermissionError: [Errno 13] Permission denied: 'b'
```

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Oct 13, 2017, 11:28

mentioned in commit b1552ea657a0d9da7ee8733334a02a2f92dc7f97

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Oct 13, 2017, 11:29

mentioned in merge request !109

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Oct 13, 2017, 11:32

Thanks for testing @aevri !

This should be fixed by the change in !109 ... of course the CI is not ensuring this, but my patch cleans things up a little bit around there and let's see we didnt break anything else in the process :)

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Oct 13, 2017, 11:46

Merged !109, this should really be fixed now.

**Comment by cs-shadow** [comment]
In GitLab by @tristanvb on Oct 13, 2017, 11:46

closed
